version: '3.8'

services:
  db:
    image: postgres:13
    container_name: gamificacao_db
    environment:
      POSTGRES_USER: gamificacao_user
      POSTGRES_PASSWORD: gamificacao_password
      POSTGRES_DB: gamificacao_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    user: postgres

volumes:
  pgdata: